// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiUsdBrzs9Vh2X4_gh4Chp1ZCx-qd4mdQ',
    appId: '1:62061827672:web:3d67faf4241ceca143dc2d',
    messagingSenderId: '62061827672',
    projectId: 'moneymate-27d12',
    authDomain: 'moneymate-27d12.firebaseapp.com',
    databaseURL: 'https://moneymate-27d12-default-rtdb.firebaseio.com',
    storageBucket: 'moneymate-27d12.firebasestorage.app',
    measurementId: 'G-MZ0K1JSTLE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVRBQNMSZwTyQkZNTOVmv9N8m9lPnqTnY',
    appId: '1:62061827672:android:cae7942a59c323bf43dc2d',
    messagingSenderId: '62061827672',
    projectId: 'moneymate-27d12',
    databaseURL: 'https://moneymate-27d12-default-rtdb.firebaseio.com',
    storageBucket: 'moneymate-27d12.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKcNDmCxpM5YSJnWJlxcxh0YM41m4y88o',
    appId: '1:62061827672:ios:fd760ea4374e410743dc2d',
    messagingSenderId: '62061827672',
    projectId: 'moneymate-27d12',
    databaseURL: 'https://moneymate-27d12-default-rtdb.firebaseio.com',
    storageBucket: 'moneymate-27d12.firebasestorage.app',
    iosBundleId: 'com.example.moneymate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKcNDmCxpM5YSJnWJlxcxh0YM41m4y88o',
    appId: '1:62061827672:ios:fd760ea4374e410743dc2d',
    messagingSenderId: '62061827672',
    projectId: 'moneymate-27d12',
    databaseURL: 'https://moneymate-27d12-default-rtdb.firebaseio.com',
    storageBucket: 'moneymate-27d12.firebasestorage.app',
    iosBundleId: 'com.example.moneymate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiUsdBrzs9Vh2X4_gh4Chp1ZCx-qd4mdQ',
    appId: '1:62061827672:web:b3a82d1e485411d943dc2d',
    messagingSenderId: '62061827672',
    projectId: 'moneymate-27d12',
    authDomain: 'moneymate-27d12.firebaseapp.com',
    databaseURL: 'https://moneymate-27d12-default-rtdb.firebaseio.com',
    storageBucket: 'moneymate-27d12.firebasestorage.app',
    measurementId: 'G-CM2EKRCK5N',
  );

}